### ISSUE TITLE
android/res/xml/config.xml loses my added <feature> tags on `prepare` with this plugin added

### ISSUE THREAD

**Issue by jschomay** [fingerproof/cordova-plugin-gapreload#1]
I'm having a problem where my android specific config.xml gets replaced with the /config.xml after prepare, and I'm sure it has something to do with your plugin's xml.  It doesn't happen on ios, and it doesn't happen without your plugin.

I noticed your plugin adds the following to my plugins/android.json (among other changes):

```
        "config.xml": {
            "/*": {
                "<access origin=\"*://192.168.10.100\" />": 1,
                "<access origin=\"*://$LIVERELOAD_HOST\" />": 1
            }
        },
```

This particular addition is not in my plugins/ios.json file.  If I delete these lines, I do not experience the issue.

Is this an issue with your plugin (likely the xml), or is it a cordova issue?
Thank you for your help!  Otherwise a very useful and fantastic plugin.

**Comment by jschomay** [comment]
To add more info, my plugins/ios.json has a similar piece of code as the android.json, but it includes all of my feature tags (which are what gets lost on prepare):

``````
        "config.xml": {
            "/*": {
                "<feature name=\"InAppPurchase\"><param name=\"ios-package\" value=\"InAppPurchase\" /></feature>": 1,
                "<feature name=\"StatusBar\"><param name=\"ios-package\" onload=\"true\" value=\"CDVStatusBar\" /></feature>": 1,
                "<preference name=\"StatusBarOverlaysWebView\" value=\"false\" />": 1,
                "<preference name=\"StatusBarBackgroundColor\" value=\"#000000\" />": 1,
                "<feature name=\"AppVersion\"><param name=\"ios-package\" value=\"AppVersion\" /></feature>": 1,
                "<feature name=\"GoogleAnalytics\"><param name=\"ios-package\" value=\"GoogleAnalyticsPlugin\" /></feature>": 1,
                "<feature name=\"Camera\"><param name=\"ios-package\" value=\"CDVCamera\" /></feature>": 1,
                "<feature name=\"Console\"><param name=\"ios-package\" value=\"CDVLogger\" /></feature>": 1,
                "<feature name=\"Device\"><param name=\"ios-package\" value=\"CDVDevice\" /></feature>": 1,
                "<feature name=\"Notification\"><param name=\"ios-package\" value=\"CDVNotification\" /></feature>": 1,
                "<feature name=\"File\"><param name=\"ios-package\" value=\"CDVFile\" /><param name=\"onload\" value=\"true\" /></feature>": 1,
                "<feature name=\"FileTransfer\"><param name=\"ios-package\" value=\"CDVFileTransfer\" /></feature>": 1,
                "<feature name=\"Geolocation\"><param name=\"ios-package\" value=\"CDVLocation\" /></feature>": 1,
                "<feature name=\"InAppBrowser\"><param name=\"ios-package\" value=\"CDVInAppBrowser\" /></feature>": 1,
                "<feature name=\"SplashScreen\"><param name=\"ios-package\" value=\"CDVSplashScreen\" /><param name=\"onload\" value=\"true\" /></feature>": 1,
                "<access origin=\"*://192.168.10.100\" />": 1,
                "<access origin=\"*://$LIVERELOAD_HOST\" />": 1
            }
        },```

Also, the android.json has code just like that, but listed for `"res/xml/config.xml"` in addition to the bit of code initially posted in the issue.
``````

**Comment by sebastien-p** [comment]
Hi,

First GapReload issue \o/ thanks for finding my plugin useful!

I managed to reproduce the issue, in fact this is pretty simple:

``` bash
$ cordova create issue && cd issue
$ cordova platforms add ios android
$ cordova plugin add org.apache.cordova.file-transfer
$ cordova plugin add pro.fing.cordova.gapreload --variable SERVER_HOST='<IP>'
```

Open _./platforms/ios/HelloCordova/config.xml_ and _./platforms/android/res/xml/config.xml_ in your favorite editor to take a look at their content, then execute `$ cordova prepare`. Now the Android file is missing some lines.

GapReload's _plugin.xml_ doesn't do a lot of things related to _config.xml_, it just whitelists `$SERVER_HOST` and `$LIVERELOAD_HOST`. To do that, and support nearly all the platforms without duplicating some code, this is what I wrote: https://github.com/fingerproof/cordova-plugin-gapreload/blob/9f7eabf027c0c74d1944dd1d07194208abfd87ba/plugin.xml#L21-L31.

My guess is Cordova Android should ignore _config.xml_ (not found) and only try to write stuff in _res/xml/config.xml_ but it doesn't and somehow overrides the latter. Whether this is a Cordova issue or intended behavior I don't know (probably a bug?). Fact is official plugins seem to rather duplicate _plugin.xml_ `config-file` declarations so I guess I should do that too.

Try `$ cordova plugin add https://github.com/fingerproof/cordova-plugin-gapreload --variable SERVER_HOST='<IP>'` (to get the latest version) and tell me if you still experience the issue.

**Comment by jschomay** [comment]
Hi Sebastian, thanks for the response.

Yes, in my case the change in f134520220cd4860ad87ced33b518666b7daa214 does indeed fix the problem :)

(Actually, I made the exact same fix locally on Friday and was going to pull request it to you on Monday, but I guess there's no need now.)

Thanks again for the fantastic plugin, my whole team was impressed when I demo'ed a css change instantly across multiple devices and platforms.  An absolute boost to our cordova development workflow.

**Comment by sebastien-p** [comment]
I'm glad this works for you :) It was an easy fix but the bug itself is kind of weird IMO.

Now that I have to duplicate `config-file` declarations, I also have to check if GapReload works on other less popular platforms like WP, FirefoxOS and others but right now I sadly don't have access to any non iOS/Android device.
