### ISSUE TITLE
command and ignore options are not available on livereload v0.9.4.0

### ISSUE THREAD

**Issue by TrySpace** [fingerproof/cordova-plugin-gapreload#6]
These two options are not available on livereload v0.9.4.0 on Windows:

```
2) Add the *hooks*, *platforms* and *plugins* subfolders to the ignore list
3) Set `cordova prepare` as the custom command to run after changes
```

**Comment by TrySpace** [comment]
I can find `excluded.txt` to ingore files/folders, but can't find where to set custom command after changes

**Comment by sebastien-p** [comment]
You're totally right, the LiveReload Windows app sadly isn't on par with its Mac OS counterpart.

But here's the good news: I also developed [a Grunt task](https://github.com/fingerproof/grunt-gapreload) for that exact reason (plus for allowing more flexible automation).

It's a bit more complex to setup but I'm sure you'll end up enjoy using it :smile:
