### ISSUE TITLE
gapreload.xml overwriting every `prepare` job

### ISSUE THREAD

**Issue by TrySpace** [fingerproof/cordova-plugin-gapreload#7]
So I save it, then run `cordova prepare` and it will re-insert $SERVER_HOST again...

```
<gapreload>
    <param name="SERVER_HOST" value="10.0.1.27" />
    <param name="SERVER_PORT" value="8888" />
    <param name="SERVER_HOST" value="$SERVER_HOST" />
    <param name="SERVER_PORT" value="$SERVER_PORT" />
    <param name="LIVERELOAD_HOST" value="$LIVERELOAD_HOST" />
    <param name="LIVERELOAD_PORT" value="$LIVERELOAD_PORT" />
</gapreload>
```

**Comment by sebastien-p** [comment]
Can you please give me more informations regarding this issue? Like the location of this file and stuff? Thanks.

**Comment by TrySpace** [comment]
`gapreload.xml` in the plugin's folder

**Comment by sebastien-p** [comment]
Oh I see. I think this sadly is a Cordova limitation. But this should not be much of an issue as GapReload only take [the first config value](https://github.com/fingerproof/cordova-plugin-gapreload/blob/master/gapreload.js#L26) into account anyway.
